import type { RoadNode, RoadGraphSegment, Ambulance, Hospital } from '@/types';

// Road network nodes around Bengaluru demo city
// The graph connects ambulance start positions to hospital destinations
// through multiple possible paths so the routing engine has alternatives.

export const ROAD_NODES: RoadNode[] = [
  { id: 'N1', latitude: 12.9756, longitude: 77.5996, name: 'Zone A Junction' },
  { id: 'N2', latitude: 12.9786, longitude: 77.5976, name: 'MG Road Intersection' },
  { id: 'N3', latitude: 12.9816, longitude: 77.6046, name: 'Outer Ring Junction' },
  { id: 'N4', latitude: 12.9686, longitude: 77.5976, name: 'Central Junction' },
  { id: 'N5', latitude: 12.9686, longitude: 77.5886, name: 'Brigade Junction' },
  { id: 'N6', latitude: 12.9656, longitude: 77.5846, name: 'Zone B Junction' },
  { id: 'N7', latitude: 12.9786, longitude: 77.5886, name: 'North-West Junction' },
  { id: 'N8', latitude: 12.9856, longitude: 77.5896, name: 'Hospital Junction' },
  { id: 'N9', latitude: 12.9720, longitude: 77.5900, name: 'Mid-City Junction' },
  { id: 'N10', latitude: 12.9626, longitude: 77.6016, name: 'South Hospital Junction' },
  { id: 'N11', latitude: 12.9750, longitude: 77.5950, name: 'City Center' },
  { id: 'N12', latitude: 12.9820, longitude: 77.5920, name: 'North Bridge' },
];

// Road segments forming a connected graph
// Multiple paths exist from N1 (ambulance start) to N8 (City Hospital)
// and from N1 to N10 (Victoria Medical Centre)
export const ROAD_GRAPH: RoadGraphSegment[] = [
  // Direct path: N1 -> N2 -> N3 -> N8 (fastest but flood-prone)
  {
    id: 'R1',
    startNode: 'N1',
    endNode: 'N2',
    start: { latitude: 12.9756, longitude: 77.5996 },
    end: { latitude: 12.9786, longitude: 77.5976 },
    name: 'MG Road Extension',
    length: 1200,
    floodRisk: 'high',
    floodDepth: 25,
    trafficLevel: 60,
    accessible: true,
    roadStatus: 'at_risk',
    estimatedTravelTime: 4,
  },
  {
    id: 'R2',
    startNode: 'N2',
    endNode: 'N3',
    start: { latitude: 12.9786, longitude: 77.5976 },
    end: { latitude: 12.9816, longitude: 77.6046 },
    name: 'Outer Ring Road East',
    length: 2100,
    floodRisk: 'low',
    floodDepth: 0,
    trafficLevel: 70,
    accessible: true,
    roadStatus: 'open',
    estimatedTravelTime: 5,
  },
  {
    id: 'R3',
    startNode: 'N3',
    endNode: 'N8',
    start: { latitude: 12.9816, longitude: 77.6046 },
    end: { latitude: 12.9856, longitude: 77.5896 },
    name: 'Hospital Link Road',
    length: 1800,
    floodRisk: 'medium',
    floodDepth: 10,
    trafficLevel: 55,
    accessible: true,
    roadStatus: 'open',
    estimatedTravelTime: 5,
  },
  // Alternative path: N1 -> N11 -> N9 -> N7 -> N8 (safer, slightly longer)
  {
    id: 'R4',
    startNode: 'N1',
    endNode: 'N11',
    start: { latitude: 12.9756, longitude: 77.5996 },
    end: { latitude: 12.9750, longitude: 77.5950 },
    name: 'City Center Approach',
    length: 900,
    floodRisk: 'low',
    floodDepth: 0,
    trafficLevel: 50,
    accessible: true,
    roadStatus: 'open',
    estimatedTravelTime: 3,
  },
  {
    id: 'R5',
    startNode: 'N11',
    endNode: 'N9',
    start: { latitude: 12.9750, longitude: 77.5950 },
    end: { latitude: 12.9720, longitude: 77.5900 },
    name: 'Mid-City Boulevard',
    length: 1100,
    floodRisk: 'low',
    floodDepth: 0,
    trafficLevel: 45,
    accessible: true,
    roadStatus: 'open',
    estimatedTravelTime: 3,
  },
  {
    id: 'R6',
    startNode: 'N9',
    endNode: 'N7',
    start: { latitude: 12.9720, longitude: 77.5900 },
    end: { latitude: 12.9786, longitude: 77.5886 },
    name: 'North-West Connector',
    length: 1400,
    floodRisk: 'low',
    floodDepth: 0,
    trafficLevel: 40,
    accessible: true,
    roadStatus: 'open',
    estimatedTravelTime: 4,
  },
  {
    id: 'R7',
    startNode: 'N7',
    endNode: 'N8',
    start: { latitude: 12.9786, longitude: 77.5886 },
    end: { latitude: 12.9856, longitude: 77.5896 },
    name: 'Hospital Approach Road',
    length: 1600,
    floodRisk: 'low',
    floodDepth: 0,
    trafficLevel: 35,
    accessible: true,
    roadStatus: 'open',
    estimatedTravelTime: 4,
  },
  // Third path: N1 -> N4 -> N5 -> N7 -> N8 (longest, goes through central area)
  {
    id: 'R8',
    startNode: 'N1',
    endNode: 'N4',
    start: { latitude: 12.9756, longitude: 77.5996 },
    end: { latitude: 12.9686, longitude: 77.5976 },
    name: 'Central Avenue',
    length: 1500,
    floodRisk: 'medium',
    floodDepth: 8,
    trafficLevel: 65,
    accessible: true,
    roadStatus: 'open',
    estimatedTravelTime: 4,
  },
  {
    id: 'R9',
    startNode: 'N4',
    endNode: 'N5',
    start: { latitude: 12.9686, longitude: 77.5976 },
    end: { latitude: 12.9686, longitude: 77.5886 },
    name: 'Brigade Road Link',
    length: 950,
    floodRisk: 'medium',
    floodDepth: 12,
    trafficLevel: 55,
    accessible: true,
    roadStatus: 'open',
    estimatedTravelTime: 3,
  },
  {
    id: 'R10',
    startNode: 'N5',
    endNode: 'N7',
    start: { latitude: 12.9686, longitude: 77.5886 },
    end: { latitude: 12.9786, longitude: 77.5886 },
    name: 'West Ring Road',
    length: 2200,
    floodRisk: 'low',
    floodDepth: 0,
    trafficLevel: 30,
    accessible: true,
    roadStatus: 'open',
    estimatedTravelTime: 5,
  },
  // Path to Victoria Medical Centre (south): N1 -> N4 -> N6 -> N10
  {
    id: 'R11',
    startNode: 'N4',
    endNode: 'N6',
    start: { latitude: 12.9686, longitude: 77.5976 },
    end: { latitude: 12.9656, longitude: 77.5846 },
    name: 'Hosur Road Stretch',
    length: 1800,
    floodRisk: 'high',
    floodDepth: 30,
    trafficLevel: 50,
    accessible: false,
    roadStatus: 'closed',
    estimatedTravelTime: 6,
  },
  {
    id: 'R12',
    startNode: 'N6',
    endNode: 'N10',
    start: { latitude: 12.9656, longitude: 77.5846 },
    end: { latitude: 12.9626, longitude: 77.6016 },
    name: 'South Hospital Road',
    length: 2000,
    floodRisk: 'medium',
    floodDepth: 5,
    trafficLevel: 40,
    accessible: true,
    roadStatus: 'open',
    estimatedTravelTime: 5,
  },
  // Cross connections for more route options
  {
    id: 'R13',
    startNode: 'N11',
    endNode: 'N12',
    start: { latitude: 12.9750, longitude: 77.5950 },
    end: { latitude: 12.9820, longitude: 77.5920 },
    name: 'North Bridge Road',
    length: 1300,
    floodRisk: 'low',
    floodDepth: 0,
    trafficLevel: 35,
    accessible: true,
    roadStatus: 'open',
    estimatedTravelTime: 4,
  },
  {
    id: 'R14',
    startNode: 'N12',
    endNode: 'N8',
    start: { latitude: 12.9820, longitude: 77.5920 },
    end: { latitude: 12.9856, longitude: 77.5896 },
    name: 'Hospital Bridge Approach',
    length: 1100,
    floodRisk: 'low',
    floodDepth: 0,
    trafficLevel: 30,
    accessible: true,
    roadStatus: 'open',
    estimatedTravelTime: 3,
  },
  {
    id: 'R15',
    startNode: 'N9',
    endNode: 'N5',
    start: { latitude: 12.9720, longitude: 77.5900 },
    end: { latitude: 12.9686, longitude: 77.5886 },
    name: 'Mid-City West Link',
    length: 800,
    floodRisk: 'low',
    floodDepth: 0,
    trafficLevel: 40,
    accessible: true,
    roadStatus: 'open',
    estimatedTravelTime: 2,
  },
];

export const EMERGENCY_AMBULANCES: Ambulance[] = [
  {
    id: 'AMB-01',
    latitude: 12.9756,
    longitude: 77.5996,
    currentZone: 'Demo Zone A',
    destinationHospital: 'City Hospital',
    routeStatus: 'at_risk',
    alternativeAvailable: true,
  },
  {
    id: 'AMB-02',
    latitude: 12.9656,
    longitude: 77.5846,
    currentZone: 'Demo Zone B',
    destinationHospital: 'Victoria Medical Centre',
    routeStatus: 'clear',
    alternativeAvailable: false,
  },
  {
    id: 'AMB-03',
    latitude: 12.9686,
    longitude: 77.5976,
    currentZone: 'Central',
    destinationHospital: 'City Hospital',
    routeStatus: 'clear',
    alternativeAvailable: false,
  },
];

export const EMERGENCY_HOSPITALS: Hospital[] = [
  {
    id: 'hospital-1',
    name: 'City Hospital',
    latitude: 12.9856,
    longitude: 77.5896,
  },
  {
    id: 'hospital-2',
    name: 'Victoria Medical Centre',
    latitude: 12.9626,
    longitude: 77.6016,
  },
];

// Map ambulances to their starting road node
export const AMBULANCE_NODE_MAP: Record<string, string> = {
  'AMB-01': 'N1',
  'AMB-02': 'N6',
  'AMB-03': 'N4',
};

// Map hospitals to their nearest road node
export const HOSPITAL_NODE_MAP: Record<string, string> = {
  'hospital-1': 'N8',
  'hospital-2': 'N10',
};
